name: Home-System
version: '${version}'
main: de.deriton.home_system_common.HomeSystem
api-version: 1.19
authors: [ Deriton ]
commands:
  sethome:
    description: Setze dein Home
    usage: /sethome [Name]
    permission: landania.homesystem.sethome
  homes:
    description: Sieh dir all deine Homes an!
    usage: /homes
    permission: landania.homesystem.homes
  delhome:
    description: Lösche ein Home
    usage: /delhome [Name]
    permission: landania.homesystem.delhome
  home:
    description: Teleportiere dich zu einem Homepunkt
    usage: /home [Name]
    permission: landania.homesystem.home
